import type { Deal } from "@/types/domain";

export const deals: Deal[] = [
  {
    slug: "jumbo-chicken-rush",
    title: "Jumbo Chicken Rush",
    status: "ongoing",
    starts_at: "2026-03-12T09:00:00.000Z",
    ends_at: "2026-03-28T22:00:00.000Z",
    hero_image: "/images/food/platter.jpg",
    product_id: "prod-chicken-classic",
    product_name: "Chicken Shawarma",
    size: "Jumbo",
    original_price: 3900,
    deal_price: 3200,
    max_quantity: 3,
    badge: "Ongoing Deal",
    teaser: "Save big on the most ordered jumbo wrap in Akure.",
    description:
      "Claim the Jumbo Chicken Rush and lock in a lower jumbo price. The wrap stays fixed at Jumbo size so the value is clean, the order is fast, and the customer sees exactly what they are getting.",
  },
  {
    slug: "suya-special-week",
    title: "Suya Special Week",
    status: "ongoing",
    starts_at: "2026-03-15T09:00:00.000Z",
    ends_at: "2026-03-21T22:00:00.000Z",
    hero_image: "/images/food/wrap.jpg",
    product_id: "prod-suya-blaze",
    product_name: "Suya Shawarma",
    size: "Special",
    original_price: 3800,
    deal_price: 3200,
    max_quantity: 3,
    badge: "Ongoing Deal",
    teaser: "Pepper-forward deal for people who want heat without paying full special price.",
    description:
      "Suya Special Week drops the Special size to a sharper price. It is claimable now, quantity-limited, and designed to move people straight into ordering without extra decision fatigue.",
  },
  {
    slug: "combo-night-drop",
    title: "Combo Night Drop",
    status: "coming-soon",
    starts_at: "2026-03-20T17:00:00.000Z",
    hero_image: "/images/food/closeup.jpg",
    product_id: "prod-combo-feast",
    product_name: "Shawarma Combo Box",
    size: "Regular",
    original_price: 5200,
    deal_price: 4600,
    max_quantity: 3,
    badge: "Coming Soon",
    teaser: "A tighter combo price for evening orders starting this week.",
    description:
      "This upcoming combo deal goes live soon. The offer is fixed, capped, and visible exactly as it will be ordered so customers cannot alter the deal contents.",
  },
  {
    slug: "turkey-weekend-fire",
    title: "Turkey Weekend Fire",
    status: "coming-soon",
    starts_at: "2026-03-27T12:00:00.000Z",
    hero_image: "/images/food/platter.jpg",
    product_id: "prod-turkey-gold",
    product_name: "Turkey Shawarma",
    size: "Special",
    original_price: 4200,
    deal_price: 3600,
    max_quantity: 3,
    badge: "Coming Soon",
    teaser: "Weekend-only turkey special lined up for the next Akure rush.",
    description:
      "Turkey Weekend Fire is a scheduled offer with a locked special-size build. Customers can preview it now, but ordering only opens once it becomes active.",
  },
  {
    slug: "beef-lunch-sprint",
    title: "Beef Lunch Sprint",
    status: "sold-out",
    starts_at: "2026-03-16T11:00:00.000Z",
    ends_at: "2026-03-18T16:00:00.000Z",
    hero_image: "/images/food/closeup.jpg",
    product_id: "prod-beef-classic",
    product_name: "Beef Shawarma",
    size: "Special",
    original_price: 3200,
    deal_price: 2700,
    max_quantity: 2,
    badge: "Sold Out",
    teaser: "Lunch crowd cleared this one early. Keep it visible so customers know what just moved.",
    description:
      "Beef Lunch Sprint reached its allocation before the timer closed. Customers can still inspect the locked details, but checkout is disabled until the next drop.",
  },
  {
    slug: "mini-wrap-flash",
    title: "Mini Wrap Flash",
    status: "expired",
    starts_at: "2026-03-01T10:00:00.000Z",
    ends_at: "2026-03-05T20:00:00.000Z",
    hero_image: "/images/food/wrap.jpg",
    product_id: "prod-mini-wrap",
    product_name: "Mini Shawarma",
    size: "Regular",
    original_price: 1750,
    deal_price: 1400,
    max_quantity: 3,
    badge: "Expired",
    teaser: "Previous flash promo now closed, kept here to show the kind of drops customers can expect.",
    description:
      "Mini Wrap Flash has ended. It remains visible as a past promotion so visitors can see the cadence and style of previous Chillington drops.",
  },
];

export function getDealBySlug(slug: string) {
  return deals.find((deal) => deal.slug === slug) ?? null;
}
